### ISSUE TITLE
Login / Signup workflow

### ISSUE THREAD

**Issue by koustuvsinha** [iem-devs/apna-library#3]
This is an epic issue to track the development of Login & Signup workflows. Sub issues : 
- [ ] Create Login Screen - #5 
- [ ] Create Signup Screen - #6  
- [ ] Allow social logins / signups - #7 
- [ ] OTP Verification - #8 
- [ ] Handle user account functions - #9
