### ISSUE TITLE
Library workflow

### ISSUE THREAD

**Issue by koustuvsinha** [iem-devs/apna-library#4]
This is an epic issue to track development of Library
- [ ] Create Updates fragment - #10
- [ ] Create Catalogs fragment - #11 
- [ ] Create Explore maps - #12 
- [ ] Library Search Functionality - #13 
- [ ] Create Fab actions - #14
